ALTER TABLE `worksheets`
  ADD COLUMN `slug` VARCHAR(191) NULL,
  ADD COLUMN `shortDescription` TEXT NULL,
  ADD COLUMN `category` VARCHAR(191) NULL,
  ADD COLUMN `subCategory` VARCHAR(191) NULL,
  ADD COLUMN `price` DOUBLE NULL,
  ADD COLUMN `discountPrice` DOUBLE NULL,
  ADD COLUMN `discountPercent` INTEGER NULL,
  ADD COLUMN `mainImageUrl` VARCHAR(191) NULL,
  ADD COLUMN `galleryImages` JSON NULL,
  ADD COLUMN `rating` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `reviewCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `soldCount` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `stock` INTEGER NULL,
  ADD COLUMN `badges` JSON NULL,
  ADD COLUMN `features` JSON NULL,
  ADD COLUMN `specifications` JSON NULL,
  ADD COLUMN `shippingInfo` JSON NULL,
  ADD COLUMN `isBestSeller` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `isPromo` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `isPublished` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

CREATE UNIQUE INDEX `worksheets_slug_key` ON `worksheets`(`slug`);
